# this workflow creates an empty commit every 50 days to prevent GitHub Actions from disabling workflows after 60 day repo inactivity
# more info: https://stackoverflow.com/questions/67184368/prevent-scheduled-github-actions-from-becoming-disabled
name: KeepAlive
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  keepalive:
    name: KeepAlive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master